import Ember from 'ember';

export default Ember.Service.extend({
  names: [
    'Hygeia HMO',
    'Total Health Trust',
    'Clearline International',
    'Healthcare International',
    'Mediplan Healthcare',
    'Multishield Nigeria',
    'United Healthcare International',
    'Premium Health',
    'International Health Management Services',
    'Songhai Health Trust',
    'Integrated Healthcare',
    'Premium Medicaid',
    'Managed Healthcare Services',
    'Princeton Health Group',
    'Maayoit Healthcare',
    'Wise Health Services',
    'Wetland Health Services',
    'Zenith Medicare',
    'Defence Health Maintenance',
    'United Comprehensive Health Managers',
    'Healthcare Security',
    'Royal Health Maintenance Services',
    'Zuma Health Trust',
    'Marfema Nigeria',
    'Prepaid Medicaid Services',
    'KBL Healthcare',
    'Sterling Health Managed Care Services',
    'Health Partners',
    'Precious Healthcare',
    'Oceanic Health Management',
    'Investcorp Medicare',
    'Greenbay Healthcare Services',
    'Medexia',
    'Royal Exchange Healthcare',
    'Marina Medical Services HMO',
    'Nonsuch Medicare',
    'Salus Trust GTE',
    'Prohealth HMO',
    'Mansard Healthplan Nigeria',
    'GNI Healthcare Nigeria',
    'Ultimate Health Management Services',
    'AVON Healthcare',
    'Regenix Health Services',
    'Redcare Health Service',
    'Harry Health Integrated Services',
    'Well Health Network',
    'Bupar Healthcare',
    'IVES Medicare',
    'Lifecare Partners',
    'DOMA Healthcare',
    'Allied HMO',
    'Police Health Maintenance',
    'NOVO Health Africa',
    'MH Healthcare',
    'Anchor HMO International Company',
    'Metrohealth HMO',
    'Greenfield Health Management',
    'Lifeworth Medicare'
  ]
});
